# Generated by Django 2.2.24 on 2021-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='catogory',
            field=models.CharField(choices=[('sa', 'Salons'), ('ch', 'Chambres'), ('cu', 'Cuisine'), ('Br', 'Bureaux'), ('tb', 'Tables')], max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
